version: '3'

services:
    video-streaming:
        image: video-streaming
        container_name: video-streaming
        build: 
            context: ./video-streaming
            dockerfile: Dockerfile
        ports: 
            - '4000:80'
        environment: 
            - PORT=80
        restart: 'no'
    
    azure-storage:
        image: azure-storage
        container_name: azure-storage
        build: 
            context: ./azure-storage
            dockerfile: Dockerfile
        ports: 
            - '4001:80'
        environment: 
            - PORT=80
            - STORAGE_ACCOUNT_NAME
            - STORAGE_ACCESS_KEY
        restart: 'no'