version: '3'

services:
    video-streaming:
        image: video-streaming
        container_name: video-streaming
        build: 
            context: ./video-streaming
            dockerfile: Dockerfile
        ports: 
            - '4000:80'
        environment: 
            - PORT=80
            - VIDEO_STORAGE_HOST=video-storage
            - VIDEO_STORAGE_PORT=8080
            - DBHOST=mongodb://db:27017
            - DBNAME=video-streaming
    
    azure-storage:
        image: azure-storage
        container_name: video-storage
        build: 
            context: ./azure-storage
            dockerfile: Dockerfile
        ports: 
            - '4001:8080'
        environment: 
            - PORT=8080
            - STORAGE_ACCOUNT_NAME
            - STORAGE_ACCESS_KEY
    
    db:
        image: mongo:4.4
        container_name: db
        ports: 
            - '4002:27017'
        restart: always