version: '3'

services:
    video-streaming:
        image: video-streaming:dev
            context: ./video-streaming
            dockerfile: dev.Dockerfile
        ports: 
            - '4000:80'
        volumes: 
            - /tmp/video-streaming/npm-cache:/root/.npm:z
            - ./video-streaming/src:/usr/src/app/src:z
        environment: 
            - PORT=80
            - VIDEO_STORAGE_HOST=video-storage
            - VIDEO_STORAGE_PORT=8080
            - DBHOST=mongodb://db:27017
            - DBNAME=video-streaming
    
    azure-storage:
        image: azure-storage:dev
        container_name: video-storage
        build: 
            context: ./azure-storage
            dockerfile: dev.Dockerfile
        ports: 
            - '4001:8080'
        volumes: 
            - /tmp/azure-storage/npm-cache:/root/.npm:z
            - ./azure-storage/src:/usr/src/app/src:z
        environment: 
            - PORT=8080
            - STORAGE_ACCOUNT_NAME
            - STORAGE_ACCESS_KEY
    
    db:
        image: mongo:4.4
        container_name: db
        ports: 
            - '4002:27017'
        restart: always

    history:
        image: history-service:dev
        container_name: history
        build: 
            context: ./history
            dockerfile: dev.Dockerfile
        volumes: 
            - /tmp/history/npm-cache:/root/.npm:z
            - ./history/src:/usr/src/app/src:z
        ports: 
            - '4003:80'
        environment: 
            - PORT=80
            - NODE_ENV=development
        